server:
  port: 8761
eureka:
  instance:
    hostname: discovery
    ip-address: 192.168.0.156
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false